#!/usr/bin/env bash
export PLUGIN_COMMAND_PREFIX="global-cert"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
export PLUGIN_CONFIG_ROOT="$DOKKU_LIB_ROOT/config/global-cert"
