#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/global-cert/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

hook-post-create-global-cert() {
  declare desc="sets global certs for an app"
  local APP="$1"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  local CRT_FILE="$PLUGIN_CONFIG_ROOT/server.crt"
  local KEY_FILE="$PLUGIN_CONFIG_ROOT/server.key"
  # todo get from platform
  local APP_SSL_PATH="$DOKKU_ROOT/$APP/tls"

  if fn-is-ssl-enabled "$PLUGIN_CONFIG_ROOT"; then
    # we symlink the global cert to the newly created app
    # this ensures that if the global cert (gc) is updated the apps, that still use the gc, have the latest gc
    mkdir -p "$APP_SSL_PATH"
    ln -s "$CRT_FILE" "$APP_SSL_PATH/server.crt"
    ln -s "$KEY_FILE" "$APP_SSL_PATH/server.key"
  fi
}

hook-post-create-global-cert "$@"
