#!/usr/bin/env bash
source "$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")" )" && pwd)/config"
source "$PLUGIN_AVAILABLE_PATH/global-cert/help-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

global-cert-default-cmd() {
  declare desc="alias for $PLUGIN_COMMAND_PREFIX:help"

  fn-help "$PLUGIN_COMMAND_PREFIX:help"
}
global-cert-default-cmd "$@"
