#!/usr/bin/env bash
source "$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")" )" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/global-cert/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

global-cert-remove-cmd() {
  #E remove the global SSL certificate
  #E dokku $PLUGIN_COMMAND_PREFIX:remove
  declare desc="removes the global SSL cert/key"
  local cmd="$PLUGIN_COMMAND_PREFIX:remove"

  if fn-is-ssl-enabled "$PLUGIN_CONFIG_ROOT"; then
    dokku_log_info1 "Removing global SSL endpoint"
    rm -rf "$PLUGIN_CONFIG_ROOT/server.crt" "$PLUGIN_CONFIG_ROOT/server.key"
  else
    dokku_log_fail "A global SSL endpoint is not defined"
  fi
}

global-cert-remove-cmd "$@"
